### ISSUE TITLE
excel series data not reloading

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#79] opened 2016-07-21 19:05 UTC
Data from a csv file is not reloaded if the csv file is changed. The option Tools->Excel, 'reload when source Excel or CSV files are modified' seems to imply that csv file data would be reloaded.

Attached is the csv file I loaded into Pisces using the Excel data import. I then changed a value in the csv file and tried clicking on the corresponding series in Pisces and it did not update. Also tried using the right-click Update option.`
[DeschutesUnregDailyFlow.csv.txt](https://github.com/usbr/Pisces/files/376765/DeschutesUnregDailyFlow.csv.txt)

**Comment by blounsbury** [comment] 2016-07-21 19:33
It appears data from an Excel file is not reloading either.

**Comment by tjrocha** [comment] 2016-07-22 03:48
Tried to test this but I can't even add an Excel series using Pisces compiled from the source code. I get as far as the first dialog and it doesn't do anything...

**Comment by blounsbury** [comment] 2016-07-22 15:03
Thanks for confirming @tjrocha. Sounds like we should also disable some of the data import options for the PISCES_OPEN version.

**Comment by blounsbury** [comment] 2016-07-22 15:12
Strange, the current code version seems to work. Maybe we just need a new release.

**Comment by ktarbet** [comment] 2016-08-27 22:02
@blounsbury  can we close this?

**Comment by blounsbury** [comment] 2016-08-29 14:59
The currently released version still exhibits the bug. Unknown if a new release would fix it or not.

**Comment by ktarbet** [comment] 2016-08-29 15:09
That is working for me.  I'm using  Version 2.0.27   August 11, 2016.
I created a blank database imported the data (Using Add Excel Series).  Then edited the CSV file with a text editor.  The clicked on the series I changed., new data appeared in the table.

**Comment by blounsbury** [comment] 2016-08-29 15:26
Hmm...don't know. I tried a csv file and it doesn't work either, strange??? Maybe @tjrocha or @robertherrera can do a test too, maybe it's just me.

![image](https://cloud.githubusercontent.com/assets/1508213/18056742/7b795d24-6dca-11e6-8d9d-abe4677a691a.png)

**Comment by ktarbet** [comment] 2016-08-29 15:40
Thanks for testing.  If you attach your test file I'll try that.  I was using the file attached at the top of this bug.  What else could be different?

**Comment by blounsbury** [comment] 2016-08-29 15:51
Test file attached. It's very confusing indeed.

[test_excel_autoupdate.csv.txt](https://github.com/usbr/Pisces/files/442773/test_excel_autoupdate.csv.txt)

**Comment by ktarbet** [comment] 2016-08-29 15:59
I was renaming the *.txt to *.csv.   If I leave the file as *.txt  -- the problem is reproduced.

**Comment by blounsbury** [comment] 2016-08-29 16:02
Yes, should rename to *.csv. Github doesn't allow attaching *.csv so I added the *.txt.

**Comment by ktarbet** [comment] 2016-08-30 15:50
Will someone please confirm this fix? 
http://www.usbr.gov/pn/hydromet/pisces/

I would like to drop plugins.txt but it is useful today.

**Comment by blounsbury** [comment] 2016-08-30 16:01
Yep, seems to have resolved the issue.

**Closed** 2016-08-30 16:40 UTC
Labels: bug
